Feature/localization
stepanenko3/nova-command-runner pull request #8
Opened 2022-10-01 17:06 UTC by drobee

Added translation functions instead of simple strings.

2022-10-01 21:45 UTC, stepanenko3 commented
@drobee,
Huge thanks

2022-10-02 07:06 UTC, arttemiuss43 requested changes

2022-10-02 07:06 UTC, arttemiuss43 commented on resources/js/pages/Tool.vue
> +                <input type="text" v-model="customCommand.command" :placeholder="this.__('Enter a Command...')" class="w-full form-control form-input form-input-bordered">
Is there a particular reason for using `this` in the template? I think it should be removed.
```suggestion
                <input type="text" v-model="customCommand.command" :placeholder="__('Enter a Command...')" class="w-full form-control form-input form-input-bordered">
```

2022-10-02 09:33 UTC, stepanenko3 commented
@drobee, We have a conflict

2022-10-03 06:48 UTC, stepanenko3 approved these changes

2022-10-03 06:48 UTC, merged

2022-10-03 06:49 UTC, drobee commented
@stepanenko3 you were too fast :) It still needs to be built, because the compiled js contains only the long-running command changes.

2022-10-03 06:57 UTC, stepanenko3 commented
@drobee, Thanks for warning me

Fixed in [4.2.2](https://github.com/stepanenko3/nova-command-runner/releases/tag/v4.2.2)

2022-10-03 07:02 UTC, drobee commented
@stepanenko3 thank you :) Would you add "HACKTOBERFEST-ACCEPTED" label to this PR please? This year I might have time to actually participate. Thanks